### ISSUE TITLE
Split up into 2 middlewares

### ISSUE THREAD

**Issue by hannesvdvreken** [h4cc/stack-psr7-bridge#2]
Hi,

Wouldn't it be more useful to have a single PSR-7 middleware that takes a StackPHP application,

and vice versa: a separate StackPHP middleware that accepts a PSR-7 next middleware as param in the invoke method?

With some shared code for the factories of course!

What do you think?

**Comment by h4cc** [comment]
I think i did it this way, because then a application can be used _both ways_ at the _same time_ :rocket: 

There may be much room for improvements, but it dont think the 4 downloads till now speak for larger refactorings currently ;)
https://packagist.org/packages/h4cc/stack-psr7-bridge

If you like to improve the few lines of code, get it on.

**Comment by hannesvdvreken** [comment]
Closing this for now. Maybe I'll come back for a PR.
